services:
  streamwavetv:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://streamwavetv-redis:6379
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      - streamwavetv-redis

  streamwavetv-redis:
    image: redis:trixie
    container_name: streamwavetv-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: