services:
  streamwavetv:
    build: .
    environment:
      REDIS_URL: redis://streamwavetv-redis:6379
    depends_on:
      - redis

  streamwavetv-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: